name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: SSWFR-JJL-WebApp
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
  AZURE_SQL_CONNECTION_STRING: "Server=${{ secrets.AZURE_SQL_SERVER_NAME }};Database=${{ secrets.AZURE_SQL_DATABASE_NAME }};User Id=${{ secrets.AZURE_SQL_USER }};Password=${{ secrets.AZURE_SQL_PASSWORD }};Encrypt=True;TrustServerCertificate=False;"


jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .Net
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

     # Install dotnet-ef tool
    - name: Install Entity Framework CLI
      run: dotnet tool install --global dotnet-ef

    # Add .NET tools to PATH using environment file
    - name: Add .NET Tools to PATH
      run: echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH

    - name: Restore
      run: dotnet restore ./BoardGameNight.sln

    - name: Build
      run: dotnet build ./BoardGameNight.sln --configuration Release --no-restore

    
    # Run xUnit tests
    - name: Run Unit Tests
      run: dotnet test ./BGN.Tests/BGN.Tests.csproj --configuration Release

    - name: Publish
      run: dotnet publish ./BoardGameNight.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

    - name: Deployment
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
